import puppeteer from "puppeteer-core";
import fs from "node:fs";
const OUT = "/private/tmp/claude-501/-Users-arch-Projects-archersdesk/ae52eed5-a030-4858-94e2-76aa19add4bc/scratchpad";
const CHROME = "/Users/arch/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing";
const jar = fs.readFileSync(`${OUT}/jar.txt`, "utf8");
const token = jar.split("\n").find((l) => l.includes("desk_session"))?.trim().split(/\s+/).pop();
const browser = await puppeteer.launch({ executablePath: CHROME, headless: true, args: ["--no-sandbox"] });
const page = await browser.newPage();
await browser.setCookie({ name: "desk_session", value: token, domain: "localhost", path: "/", httpOnly: true });
page.on("console", (m) => { if (m.type() === "error" || m.type() === "warning") console.log(`[${m.type()}]`, m.text().slice(0, 600)); });
page.on("pageerror", (e) => console.log("[pageerror]", String(e).slice(0, 600)));
await page.goto("http://localhost:3000/", { waitUntil: "networkidle0", timeout: 30000 });
await new Promise((r) => setTimeout(r, 2500));
await browser.close();
console.log("console check done");
